### PR TITLE
Brian solutions

### PR DESCRIPTION
**Pull request by brianthiel**
Here are my solutions!

### CODE REVIEW

**Comment by 6zz** [comment]
@jasonly we would need to create a brian-solutions branch to merge this into

**Comment by jasonly** [comment]
Sweet! Thanks! Branch made, can you change the branch from master to brian-solutions

**Comment by brianthiel** [comment]
PR updated to merge into `brian-solutions` branch

**Review by jasonly — APPROVED** [review]

**Comment by jasonly** [comment]
TYTYTY!

**Pull request merged**
